src/@orb.yml
If `sudo` is not installed this orb installs the incorrect package off of PyPI, `aws`. This pull request fixes that issue to install the correct package `awscli`.
https://pypi.org/project/aws/
https://pypi.org/project/awscli/
=> Install the correct package from pypi

src/@orb.yml
Fixes #13.
If the AWS CLI is already installed, the `install` command will now let you know via echo and just exit successfully.
=> Make install more intelligent.

.circleci/config.yml, src/@orb.yml
The install command will now only install when the aws cli is missing. Added this command to the configure command and renamed configure to "setup". Updated read me. Added example
=> Replace "configure" with "setup"

.github/ISSUE_TEMPLATE/bug.md, .github/PULL_REQUEST_TEMPLATE.md
This MR introduces issue und pull-request templates with the same format as the ones from https://github.com/CircleCI-Public/circleci-orbs/tree/staging/.github.
This increases the UX for CircleCI orbs across the different projects :)
=> feat: add issue and pull request template, based on the ones from the other CircleCI orbs

README.md
aws-cli/configure has been renamed to aws-cli/setup.
aws-cli/configure has been renamed to aws-cli/setup.
=> aws-cli/configure -> aws-cli/setup

.circleci/config.yml, src/@orb.yml
Resolves https://github.com/CircleCI-Public/aws-cli-orb/issues/30 by adding an option to skip the installation check. This is useful when an executor image comes with an older version of the aws CLI pre-installed, but the user wishes to use the orb to install the latest version. (Currently the orb would detect the existing installation and skip the install)
=> Add skip-install-check parameter

.circleci/config.yml, src/commands/install.yml, src/commands/setup.yml
As seen in https://github.com/CircleCI-Public/aws-cli-orb/issues/41, a breaking change in AWS CLI v2 is that it now relies on a paging command to be installed on the system: https://docs.aws.amazon.com/cli/latest/userguide/cliv2-migration.html#cliv2-migration-output-pager
By default it looks for `less` on *ix systems. Some CircleCI images (or custom images) do not have this command installed by default (this happened to me with `circleci/python:3.7`) which will have some `aws` commands fail with:
```
[Errno 2] No such file or directory: 'less': 'less'
```
A broken public build can be found here: https://app.circleci.com/pipelines/github/offen/docs/92/workflows/e6f75939-12b0-4ff8-a41a-613d7349f9a6/jobs/62
This PR checks whether `less` is installed and in case it isn't and it can install it …
=> fix: when installing v2, set empty AWS_PAGER var [semver:minor]

.circleci/config.yml, src/commands/install.yml
Changes:
- Add an executor with aws v2 preinstalled, to the integration tests
- Fix behavior of orb when there is an existing v2 installation by adding `--update` flag when needed (see https://github.com/CircleCI-Public/aws-cli-orb/commit/68876240873e0fb5bd247924e174682f0756bcbd for example of error when `--update` is not set)
- Also detect `python3`
=> Support overwriting existing v2 installation

src/commands/install.yml
This is a proposed fix for the following issue:
https://github.com/CircleCI-Public/aws-cli-orb/issues/50
I believe the newly implemented if/else statement was always resulting in the `else` and causing failed builds when the AWS CLI tool was already installed.
This change adds brackets around the conditional to check if the `skip-install-check` parameter is false to ensure the check is made and the right part of the code is executed.
=> add brackets for if statement check [semver:patch]

src/commands/install.yml
Installing awscli v2 generates so much output you can't even view it in the CircleCI web UI
```
Your output is too large to display in the browser.
Only the last 400000 characters are displayed.
```
Quieten unzip output.
=> [semver:patch] Quieten unzip output

src/commands/install.yml
We have `set -u` set on all CI steps, which fails when this orb checks if `AWS_PAGER` is set
Update checking existence of bash variables with `${FOO:-}` syntax
=> [semver:patch] Make orb 'nounset' safe

src/commands/install.yml
* When AWS_PROFILE is set in the environment, aws-cli version 1 will error when `aws --version` is run prior to that profile being configured.
Avoid this by unsetting AWS_PROFILE when running `aws --version`.
=> Fix install errors when AWS_PROFILE is set [semver:patch]

src/commands/setup.yml
I'm persisting the .aws folder to the workspace to reuse ready profiles in other jobs. Unfortunately in the current setup, there are only credentials that are set for the profile. The region remains unset for the profile (it's set only for default profile).
add an option to configure a region for a non-default profile
add a parameter configure-profile-region that works in the same fashion as configure-default-region.
add a step "Configure AWS profile region" that works in the same fashion as "Configure AWS default region".
=> [semver:minor] added an option to configure a region for a non-default profile

src/scripts/install.sh
- nothing new is added
- no new features
- not necessary
I met a bug when running `install` with `override-installed: true` .
When `$AWS_PATH` is NOT actually a symbolic link, removing `$AWS_SYMLINK_PATH` fails because of the following error:
`rm: invalid option -- 'w'`
This is caused because `sed` command does not work as expected and `$AWS_SYMLINK_PATH` starts with the permissions like `-rwx...` .
`$AWS_SYMLINK_PATH` will be set only when `$AWS_PATH` is symlink, so that an empty string will be passed to `rm` command otherwise.
=> [semver:patch] set AWS_SYMLINK_PATH only when AWS_PATH is symlink

src/scripts/install.sh
I found a typo while looking at the CI execution log.
Fixed a typo.
`AWS CLI is already installed, skipping isntallation.`
↓
`AWS CLI is already installed, skipping installation.`
=> [semver:patch] Fixed a typo in the message when cli is already installed.

src/commands/install.yml
We don't actually use pip to install the CLI anymore. Oops.
Reverts CircleCI-Public/aws-cli-orb#87
=> Revert "[semver:patch] docs: update description on installing AWS CLI"

.circleci/test-deploy.yml, src/commands/install.yml, src/commands/setup.yml, src/scripts/assume-role-with-web-identity.sh, src/scripts/install.sh, src/scripts/role-arn-setup.sh
=> fix:v3.1.1

src/scripts/assume-role-with-web-identity.sh
This `PR` makes the `assume-role-with-web-identity` script posix compliant so that it can be ran in `Alpine` linux
=> fix: made script posix compliant

src/commands/setup.yml
- [ n/a ] All new jobs, commands, executors, parameters have descriptions
- [ n/a ] Examples have been added for any significant new features
- [ n/a ] README has been updated, if necessary
The `aws-secret-access-key` parameter's description (`setup` command) references the name of the environment variable preceded by `$`, instead of just the environment variable's name. This is incorrect and could create confusion.
Remove the `$` (Dollar sign) that's currently preceding the environment variable's name.
=> [semver:skip] Fixing typo in parameter description 

src/scripts/assume-role-with-web-identity.sh
This `PR` adds validation to the `assume-role-with-web-identity` command. The command will fail if the `aws cli` is not installed or if no `OIDC token` is available.
=> fix: added error messages for missing parameters

src/scripts/assume-role-with-web-identity.sh
This `PR` cleans up the `assume-role-with-web-identity` script and addresses the `shellcheck` errors.
=> fix: addressed shellcheck errors

src/scripts/configure.sh
Alpine linux does not source environment variables in between steps. This `PR` adds that ability
=> fix: source env vars for alpine linux

src/scripts/install.sh
This `PR` fixes an issue that's causing the installation of the `aws-cli` to fail on `Alpine`.  
The issue is caused by an error with installing `glibc` on linux through `apk`.
=> fix: added --force-overwrite flag to fix glibc install

.circleci/config.yml, .circleci/test-deploy.yml, src/commands/assume-role-with-web-identity.yml, src/scripts/assume-role-with-web-identity.sh
A new version of the OIDC token has been published, to allow for additional claims. 
The new value is `org/ORGANIZATION_ID/project/PROJECT_ID/user/USER_ID/vcs-origin/VCS_ORIGIN/vcs-ref/VCS_REF`, a string, where `ORGANIZATION_ID`, `PROJECT_ID`, and `USER_ID` are UUIDs that identify the CircleCI organization, project, and user, respectively. The user is the CircleCI user that caused this job to run. VCS_ORIGIN and VCS_REF are strings that identify the repo URL and reference to the change that caused the job to run.
Updated instances of `$CIRCLE_OIDC_TOKEN` to `$CIRCLE_OIDC_TOKEN_V2`, and also updated the orb tools orb version from 11.1 to 11.6
=> feat: update to oidc token v2

src/commands/setup.yml, src/examples/configure_role_arn.yml, src/examples/install_aws_cli.yml, src/examples/install_aws_cli_with_web_identity.yml, src/executors/default.yml, src/scripts/configure.sh
Currently if the in the `config.sh` script, we run `. $BASH_ENV` in `Alpine Linux` to access environment variables passed from a previous step. However, if `$BASH_ENV` has not been created before this script is run, the build fails with this error:
```
/bin/bash: line 3: /tmp/.bash_env-63ff46c43d2fa51fdd8a6998-0-build: No such file or directory
```
To fix this issue, we must run `touch $BASH_ENV` first as suggested in this Discuss post:
https://support.circleci.com/hc/en-us/articles/360048353271-Accessing-BASH-ENV-Results-in-No-such-file-or-directory-
=> fix: add touch to initialize $bash_env

.circleci/test-deploy.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/role_arn_setup.sh
Currently, job name containing white spaces is valid in CircleCI. However, the `assume-role-with-web-identity` command uses the job name as the default value for the `role-session-name` parameter that gets passed to the `aws cli`. 
The issue is that the `aws cli` command does not accept a `role-session-name` contain white spaces and throws this error: 
`Member must satisfy regular expression pattern: [\w+=,.@-]*`
This `PR` implements a fix to check and see if the job name contains  white spaces. It it does, the spaces are replaces by `-`.
=> fix: role session name

.circleci/test-deploy.yml, src/commands/assume_role_with_web_identity.yml, src/commands/install.yml, src/commands/role_arn_setup.yml, src/commands/setup.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh, src/scripts/install.sh, src/scripts/role_arn_setup.sh
When a user specifies a shell for an executor in their config, using `shell: /bin/bash -o nounset` causes scripts with unbound variables to fail. 
This `PR` resolves this issue.
=> fix: nounset shell

.circleci/test-deploy.yml, src/commands/setup.yml, src/scripts/configure.sh
This `PR` updates the descriptions of the `configure_default_region` and the `configure_profile_region` parameters. It also removed the `--profile` flag from the `aws configure set default.region` cli command in the `configure.sh` script. Lastly, it adds testing and validation for configuring both the default region and the profile region. 
Currently, there's some confusion regarding the configuration of the `default region` versus the `profile region`. 
According to the `AWS` Documentation: 
**`aws configure set default.region`**:
- This command sets the default region for the AWS CLI. The specified region will be used by default for all AWS CLI commands unless overridden.
-The value set using default.region is stored in the AWS CLI configuration file (`~/.aws/config`), specifically in …
=> fix: set default region

.circleci/test-deploy.yml, src/commands/setup.yml, src/scripts/configure.sh, src/scripts/install.sh
When trying to run the `aws-cli/setup` command on the `Terraform` image (`Apline`), the installation of the CLI fails  with this error:
`curl: (48) An unknown option was passed in to libcurl`
This `PR` adds `libcurl` in order to fix this issue
=> fix:terraform image install

.circleci/test-deploy.yml
The MacOS tests for this orb are still making use of the [deprecated](https://discuss.circleci.com/t/macos-resource-deprecation-update/46891) medium MacOS resource class.
This version will not have any further [Xcode version support](https://discuss.circleci.com/t/reminder-no-new-xcode-version-support-on-macos-medium-large-resources/46890) and as such, we should set an example by updating to the Gen2 resource class.
Add a `resource_class` stanza to update the various MacOS tests to use `macos.x86.medium.gen2` from `medium`
=> chore: update MacOS executor to use Gen2

src/scripts/install.sh
This install command will not work:
```
- aws-cli/install:
override_installed: true
```
It will attempt to download the zipfile from a path including "latest", eg `https://awscli.amazonaws.com/awscli-exe-linux-x86_64latest.zip`. There's no zipfile there.
In the `install` command, if `override_installed` is set to `true` but `version` is not specified, the orb will attempt to download the AWS CLI from a path including "latest". Change this behavior so that it instead does not include any version identifier in the zipfile URL.
This behavior already exists here, but the functionality was never added to the block reached when `override_installed` is set to true: https://github.com/CircleCI-Public/aws-cli-orb/blob/8f0d172b929d87457b64c027390e3bdcb3eb8ef9/src/scripts/install.sh#L133-L135
=> Allow override_installed without specifying version

src/commands/assume_role_with_web_identity.yml, src/commands/setup.yml, src/scripts/assume_role_with_web_identity.sh
Switching `AWS_REGION` environment variable so that the `assume-role-with-web-identity` command can run without the region flag is cumbersome. 
add region flag to `assume-role-with-web-identity` cli call. This will remove the need to update environment variables when targeting non-default regions.
=> ADD region flag to assume-role-with-web-identity

.circleci/test-deploy.yml, src/commands/assume_role_with_web_identity.yml, src/commands/install.yml, src/commands/role_arn_setup.yml, src/commands/setup.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh, src/scripts/install.sh, src/scripts/linux/install.sh, src/scripts/macos/install.sh, src/scripts/role_arn_setup.sh, src/scripts/utils.sh, src/scripts/windows/install.sh
This `PR` contains the following feature and bug fixes: 
- https://github.com/CircleCI-Public/aws-cli-orb/pull/152
- https://github.com/CircleCI-Public/aws-cli-orb/pull/151
- https://github.com/CircleCI-Public/aws-cli-orb/pull/149
=> feat: features and bug fixes from pull requests

.circleci/test-deploy.yml, src/commands/setup.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh, src/scripts/install.sh, src/scripts/role_arn_setup.sh
Currently, the orb does install the `aws cli` version that's specified by the user. This `PR` fixes this issue.
=> fix: install specified version

.circleci/test-deploy.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh, src/scripts/linux/install.sh
The current version of the orb exports the `OIDC` credentials to `$BASH_ENV`. 
In cases where multiple profiles are created, some `aws` commands will use the credentials from `$BASH_ENV` by default, bypassing any profiles that's specified. 
This `PR` writes the generated `OIDC` keys to a temporary file that's `sourced` to complete the configuration process.
=> refactor:write oidc credentials to temp file

.circleci/test-deploy.yml, src/@orb.yml, src/examples/configure_role_arn.yml
This `PR` adds additional checks to the `integration-test-role-arn-setup` test. 
After it executes the `aws-cli/role_arn_setup` command, it logs into `aws ecr` using the profile that's been configured.
=> ci: add more testing for role_arn_setup command

src/scripts/assume_role_with_web_identity.sh
The other parameters in `assume_role_with_web_identity` allow for env substitution, but `session_duration` does not. This change simply adds env substitution in the same exact pattern as the others.
This is needed so we can pass in an environment variable as the value for session duration. We have our own private orb that we're wrapping this command in and we're calculating the needed session_duration in a previous step and saving it to BASH_ENV, where we can then pass it in to `assume_role_with_web_identity`.
- add `circleci env subst` to `session_duration` parameter of `assume_role_with_web_identity` command.
=> Allow for `session_duration` env substitution

src/scripts/assume_role_with_web_identity.sh
* Replace all invalid characters with '-'
* Trim length to 64 chars
When passing an invalid role session name, we don't want jobs to explode. Fix the role session name as best we can and proceed.
This especially helps in situations where a role session name is constructed from variables of unknown length, for example if the repo/branch name or commit subject are included.
=> Improvements to role session name sanitisation

.circleci/test-deploy.yml, src/scripts/assume_role_with_web_identity.sh
The `role_session_name` parameter can only contain `64` characters and can only contain uppercase and lowercase letters, digits from 0-9, and the characters `=`,`,`,`.`, `@`, `_`, and `-`.
This pull request sanitizes the `role_session_name` parameter, ensuring that it's properly formatted so that the `assume_role_with_web_identity` command does not fail. It also adds testing for this parameter as well.
=> feat: sanitize role session name

.circleci/test-deploy.yml, src/scripts/assume_role_with_web_identity.sh
Some user store the `session_duration` parameter as an environment variable. 
This pull request expands the environment variables that users set. It also adds testing for this specific use case
=> feat: expand session duration

.circleci/test-deploy.yml, src/scripts/linux/install.sh
Some users are reporting failures with the `aws-cli/install` command on different versions of `Alpine Linux`. 
This `PR` fixes the issue by updating and upgrading `apk` before installing `curl`
=> fix: install curl on alpine linux

.circleci/test-deploy.yml, src/scripts/windows/install.sh
Currently in the `aws-cli/install` command, when the `override_installed` parameter is set to `true` without a specified `version` in `windows`, the `latest` version of the `aws-cli` is installed. However, users are getting the following error: 
```
bash: aws: command not found
```
The `PATH` is not set for the latest version because the script checks for only checks for `2.` in the version string but not `latest` as well. 
This pull request add additional validation so that the correct `PATH` is set when the version string is equal to `latest`.
=> fix: override installed windows

.circleci/test-deploy.yml, src/commands/assume_role_with_web_identity.yml, src/commands/setup.yml, src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh
Currently, the `assume_role_with_web_identity` command generates temporary AWS keys that gets written to a temporary file, enabling users to create multiple profiles without having to alter `BASH_ENV`. This was helpful for users who ran workflows requiring multiple profiles to run their `aws` commands. 
However, this change broke for many users (see #179) who were relying on the AWS key being written to `BASH_ENV`. 
This pull request adds ads the `set_aws_env_vars` parameter to the `assume_role_with_web_identity` command that enables to write the keys to a temporary file when set to `false`. Otherwise, it automatically writes to `BASH_ENV` by default.
=> feat: set_aws_env_vars

src/scripts/install.sh
Currently, the `disable_aws_pager` parameters is only applied  if the AWS CLI was initially absent or if another version is being installed. If the `aws-cli` is already installed, the parameter is ignored. 
This `PR` ensures that the parameter is always applied
=> fix: add pager validation for every install case

.circleci/test-deploy.yml, src/scripts/install.sh
If a user specifies a version of the `aws cli` to install, the orb always uninstalls the any pre-installed version before installing the specified one. It does not check to see if the user's specified version is already installed. 
This `PR` checks to see if the the user's version matches the pre-installed version of the `aws-cli`. If it does, it skips the installation process.
=> refactor: skip installation if specified version is installed

.circleci/test-deploy.yml, src/scripts/configure.sh
The apple silicon are not able to use the classic install method due to arquitectural differences. I updated the install function to install from source code.
=> Fix installation of cli on mac os.

src/commands/assume_role_with_web_identity.yml, src/examples/configure_role_arn.yml, src/examples/install_aws_cli.yml, src/examples/install_aws_cli_with_web_identity.yml
this helps users to call `assume_role_with_web_identity` command without calling `setup` command.
eg:
```
jobs:
aiaws-bedrock:
executor: python
environment:
AWS_REGION: us-east-1
steps:
- checkout
- aws-cli/assume_role_with_web_identity:
role_arn: $CIRCLE_AWS_ROLE_ARN
role_session_name: "cci-oidc-session"
```
instead of 
```
jobs:
aiaws-bedrock:
executor: python
environment:
AWS_REGION: us-east-1
steps:
- checkout
- aws-cli/setup:
role_arn: $CIRCLE_AWS_ROLE_ARN
role_session_name: "cci-oidc-session"
- aws-cli/assume_role_with_web_identity:
role_arn: $CIRCLE_AWS_ROLE_ARN
role_session_name: "cci-oidc-session"
```
=> chore: setup automatically on assume role with web identity command

.circleci/test-deploy.yml, src/commands/setup.yml, src/scripts/configure.sh
On issue #198 and #139 there was presented an issue, where doing multiple setup, one with oidc and then one with env, caused the second one to have an authentication error. This was due to a wrong configuration on the job, but also a bug on the validations on the configure script. 
Here I'm fixing that and also adding new tests to validate this behavior.
=> fix: Multiple setups not doing the right configuration

.circleci/test-deploy.yml, src/commands/setup.yml, src/scripts/configure.sh
The configure script was still managing the static credentials as if they were environment_variable type, and they are string now.
I'm updating the defaults and the script to work as they are supposed to, and adding a new test that validate the setup when using static credentials authentication.
=> Resolves issues with static credentials auth and add tests

src/commands/setup.yml
I'd like to use this orb to setup AWS access and secret tokens using an OIDC role without running through the AWS CLI install steps.
Adds a flag to the `aws-cli/setup` job to skip the AWS CLI install step.
=> add disable_aws_install flag to setup

src/scripts/assume_role_with_web_identity.sh
#221 had a small bug where it would exit 0 and end the script if the new tokens were minted. This would require you to run `aws-cli/setup` twice. 
This fixes that bug by only exiting if the tokens do not mint.
=> Update script to not exit 0 when the OIDC token is set

src/scripts/assume_role_with_web_identity.sh, src/scripts/configure.sh
[CircleCI supports passing environment variables between steps](https://circleci.com/docs/set-environment-variable/#set-an-environment-variable-in-a-shell-command) using the file specified in "$BASH_ENV". The `assume_role_with_web_identity` script forces the use of `sh` as the shell, and therefore doesn't have access to environment variables specified in previous steps, as it is not loaded automatically into the shell environment. 
As such, if a user leverages the orb in the following way, but specified values for the environment variables in $BASH_ENV, `assume_role_with_web_identity` will fail:
```yaml
- aws-cli/setup:
role_arn: $OIDC_IAM_ROLE_ARN
region: $OIDC_AWS_REGION
```
- Updates `assume_role_with_web_identity.sh` to source $BASH_ENV to load any environment variables written to …
=> Update web identity role assumption to support parameters that reference environment variables set with $BASH_ENV

src/scripts/assume_role_with_web_identity.sh
Token retry doesn't work as it doesn't populate value needed in later steps.
One line ~50 the script needs the V2 token which is never populated as part of the retry loop, so the retry loop as written cannot ever produce data needed by the step below:
```bash
$(aws sts assume-role-with-web-identity \
--role-arn "${AWS_CLI_STR_ROLE_ARN}" \
--role-session-name "${AWS_CLI_STR_ROLE_SESSION_NAME}" \
--web-identity-token "${CIRCLE_OIDC_TOKEN_V2}" \
--duration-seconds "${AWS_CLI_INT_SESSION_DURATION}" \
"$@" \
--query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
--output text)
```
See https://github.com/CircleCI-Public/aws-cli-orb/issues/227
=> sets v2 version of token for local script usage

src/commands/install.yml, src/commands/role_arn_setup.yml, src/commands/setup.yml
1. Propagate 'when' parameter to the script execution steps which allows to run aws cli scripts conditionally depending on a workflow status 'on_success', means the script will run only if all previous steps were successful 'on_fail' means the script will run if any previous step fails 'always' means it will run regardless of the success or failure of previous steps in the workflow
2. Default value set to 'on_success' in order to preserve current behavior
In some cases aws-cli setup should be executed even when the previous step of the workflow failed.  
As an example, we upload test results to an s3 no matter if tests passed or failed.  
Right now aws-setup can't be called for any previous step of the workflow failed.
This changes allow to propagate 'when' parameter (behavior borrowed …
=> Allow CLI commands to be always executed
